### ISSUE TITLE
Dataset selection Fixes

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/air-pollution#29]
- [ ] Have dropdown for City filter based on Province Selection
- [ ] ALL checkbox to update selection i.e selects all pollutants and deselects all pollutants when ALL deselected

**Comment by elenagan** [comment]
Maybe we can use pickerInput instead of checkboxes as it has Select All and Deselect All included

**Comment by netsgnut** [comment]
I have made some updates to the behaviour of the city/province dropdowns in my map PR. Feel free to review the implementation to see if it makes things better
