### ISSUE TITLE
Lack of Data

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/air-pollution#31]
We don't have data on all pollutants for all provinces. For example the Yukon only has 5 out of the 8
Same with specific cities within provinces - may lead to issues for other plots?

**Comment by netsgnut** [comment]
This problem may be related to the 2020 data (probably [due to COVID](https://open.canada.ca/data/en/dataset/1b36a356-defd-4813-acea-47bc3abd859b)).

> Beginning in March of 2020 the impact of the COVID-19 pandemic on NAPS Operations has resulted in reduced data availability for some sites and parameters.

I have made a PR (#34) to use the 2016-2020 data instead. It might not solve this problem completely, but probably can provide better coverage?
