### ISSUE TITLE
[M4] Submission

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/air-pollution#46]
Please reply your enhancement description in the format below:

Modification: [Describe what you did]
Source: [paste the link to the comment]
Team Member: [Your Name]
Commit(s): [Link to the commit(s) where you incorporated the modification]

**Comment by netsgnut** [comment]
Modification: Add additional information (min/mean/max) of the measurements to the map
Source: https://github.com/UBC-MDS/air-pollution/issues/47 (which comes from a chat message)
Team Member: @netsgnut 
Commits: f62e4807b3b1b88628514847b6c42ace4bb68585

**Comment by netsgnut** [comment]
Modification: Allow NAPSID to be filtered
Source: From a chat message
Team Member: @netsgnut 
Commits: 9fb347b7680666f0502af0247cd49f6ce1a52db3

**Comment by elenagan** [comment]
Modification: Added Generate Report Functionality
Source: From Lecture
Team Member: Elena Ganacheva
Commit(s): https://github.com/UBC-MDS/air-pollution/commit/a8252385cf82490a3ac91a95e1a70d6032f848bf

**Comment by ranjitprakash1986** [comment]
Modification: Added Seasonal Plot showing the average monthly pollutant levels
Source: Group discussion
Team Member: Ranjit Sundaramurthi
Commit(s): [4dc0b44](https://github.com/UBC-MDS/air-pollution/commit/4dc0b44d87f8efb2d6e3fe3fe9f5d7a64e56d477)

**Comment by ritisha2000** [comment]
Modification: Added description of the pollutants and instructions to deselect
Source: Group discussions
Team Member: Ritisha Sharma
Commit(s): https://github.com/UBC-MDS/air-pollution/commit/037f74a134333f1743b6babdb6b39281b7bb7534

**Comment by ritisha2000** [comment]
Modification: Make plots into plotly to add tooltip
Source: Group discussions
Team Member: Ritisha Sharma
Commit(s): https://github.com/UBC-MDS/air-pollution/commit/0fb60b850a9ccd4b9f4dbbf1c78a8f0241b9e1f8
